name: ci
on: [push,pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into working directory
        uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      
      - name: Set Permissions on scripts.
        run: chmod u+x *.sh

      - name: Build Classes
        run: ./build.sh
 
      - name: Run Unit Tests
        run: ./run-tests.sh
            

